### ISSUE TITLE
CSVのoptional指定のデフォルト挙動(値が空の時)を考える

### ISSUE THREAD

**Issue by shopper29** [Yuuki77/multi-container-account-manager#1]
- 色
  - 全て水色で作られる
- アイコン
  - 全てfingerprintで作られる

ただ、実際に使用する際には色を意識しないので、デフォルトで"良い感じ"に色が変わっていると使いやすくて良さそうです！

**Comment by Yuuki77** [comment]
ありがとうございます！いい感じになにか設定するようにしました！
